/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentItem: typeof import('./src/components/comment-item.vue')['default']
    CommentList: typeof import('./src/components/comment-list.vue')['default']
    Comments: typeof import('./src/components/comments.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LButton: typeof import('./src/base/L-Button.vue')['default']
    LCard: typeof import('./src/base/L-Card.vue')['default']
    LIcon: typeof import('./src/base/L-Icon.vue')['default']
    LLoading: typeof import('./src/base/L-Loading.vue')['default']
    LPagination: typeof import('./src/base/L-Pagination.vue')['default']
    LTab: typeof import('./src/base/L-Tab.vue')['default']
    LTitle: typeof import('./src/base/L-Title.vue')['default']
    MvCard: typeof import('./src/components/mv-card.vue')['default']
    Player: typeof import('./src/components/player.vue')['default']
    PlayIcon: typeof import('./src/components/play-icon.vue')['default']
    PlaylistCard: typeof import('./src/components/playlist-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongCard: typeof import('./src/components/song-card.vue')['default']
    SongTable: typeof import('./src/components/song-table.vue')['default']
    TopPlaylistCard: typeof import('./src/components/top-playlist-card.vue')['default']
    User: typeof import('./src/components/user.vue')['default']
  }
}
