/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LButton: typeof import('./src/base/LButton.vue')['default']
    LCard: typeof import('./src/base/LCard.vue')['default']
    LConfirm: typeof import('./src/base/LConfirm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
